### ISSUE TITLE
找不到打分文件./data/movie/ratings_final.txt

### ISSUE THREAD

**Issue by kepsail** [hwwang55/GCNRec#1]
OSError: ../data/movie/ratings_final.txt not found.

File "D:\projects\KGCN\src\data_loader.py", line 21, in load_rating
    rating_np = np.loadtxt(rating_file + '.txt', dtype=np.int64)

**Comment by johnnyjana730** [comment]
same issue

**Comment by hwwang55** [comment]
Hi, please see README - running the code - movie for details. Thanks.
