### ISSUE TITLE
question about computing user-relation score

### ISSUE THREAD

**Issue by AlexYangLi** [hwwang55/GCNRec#10]
![image](https://user-images.githubusercontent.com/30424821/64943253-dc5c1c80-d89d-11e9-84e8-c55d75a9ab5a.png)

Hi, Wang! Should we use `tf.reduce_sum`  to compute `user_relation_scores` instead of `tf.reduce_mean`？ Since you said it's a inner product operation in the paper. Thanks in advance.

**Comment by hwwang55** [comment]
Hi! Yes it should be reduce_sum if we use inner product here.
