### ISSUE TITLE
关于预测的问题

### ISSUE THREAD

**Issue by Aliang-CN** [hwwang55/GCNRec#11]
你好，我在写预测模块的时候，发现预测的数据量跟训练模型的batch_size有关，预测的时候喂的数据量必须和模型训练时的batch_size相等才可以预测出结果，我想咨询一下这个是什么原因引起的？

**Comment by hwwang55** [comment]
你好！这是因为模型里用到了batch_size这个变量，所以这个模型是需要预先给定batch_size的值的。在模型里把batch_size固定的原因是代码里的有些reshape操作的需要。谢谢！

**Comment by Aliang-CN** [comment]
我已经把你代码里面reshape和batch_size有关的操作已经修改了，现在预测的时候，可以任意batch_size。你这个模型真的很优秀，在我自己的数据集上面表现很优秀。
