### ISSUE TITLE
Request of Book-Crossing Dataset

### ISSUE THREAD

**Issue by daiquanyu** [hwwang55/GCNRec#12]
Dear Dr. Wang,

Thanks for your wonderful work and clear implementation. I wonder whether you could provide a copy of your processed Book-Crossing dataset with knowledge graph as described in the paper. My e-mail address is dqyzm100@gmail.com. Thanks again.

Best

**Comment by hwwang55** [comment]
Hi! The Book-Crossing dataset can be found in https://github.com/hwwang55/RippleNet. Thanks!

**Comment by daiquanyu** [comment]
Hi, 

Thanks for your quick reply. I would like to ask one more question about the experiments of Book-Crossing. I couldn't reproduce the results of CTR prediction on this dataset when I directly obtained it from RippleNet although I set the all the hyperparameters as your paper suggests. Specifically, I only got the following results with 3 runs under the recommended settings (dataset:book aggregator:sum n_epochs:20 neighbor_sample_size:8 dim:64 n_iter:1 batch_size:256 l2_weight:2e-05 ls_weight:0 lr:0.0002 ratio:1 ):
  - average auc: 0.6909+\-0.0017
  - average f1 : 0.6374+\-0.0003
where there is very large gap as presented by the paper.

I don't whether it is because of the dataset configuration or not. Could you give some advice on this? Thank you so much.

Best

**Comment by hwwang55** [comment]
Hi there, I'm not sure if the KG for the book crossing dataset in the two models are identical. The reason might be the different KGs used in the two repositories since the KG is important for both models. The experiment on this dataset is not done by me, but I will check it out later. Thanks.

**Comment by daiquanyu** [comment]
Hi,

Thanks again. I look forward to your reply. Hope that you could share a copy of your original dataset with me if it is different from that of RippleNet.

Best

**Comment by hguomin** [comment]
> Hi there, I'm not sure if the KG for the book crossing dataset in the two models are identical. The reason might be the different KGs used in the two repositories since the KG is important for both models. The experiment on this dataset is not done by me, but I will check it out later. Thanks.

Hello Dr. Wang, how about the experiment on the book crossing dataset now? could you please provide the dataset and it's parameter setup for us as reference? Much thanks @hwwang55 .
