### ISSUE TITLE
Where is kg.txt come from?

### ISSUE THREAD

**Issue by SSSxCCC** [hwwang55/GCNRec#13]
Hi, I am learning knowledge graph based recommender system, and your work is great!
However I have some trouble getting the dataset. For the movielens dataset I know where to download, but for the kg.txt file, I don't know where it comes from. I can't get access to the website https://www.satori.com/. So where do you get the satori knowledge graph dataset?

**Comment by SSSxCCC** [comment]
When I get https://www.satori.com/, I get a 504 error.
![satori](https://user-images.githubusercontent.com/24839738/69119239-e9310280-0ad0-11ea-8130-c1c55f165d34.png)

**Comment by hwwang55** [comment]
Hi! The kg.txt is extracted from Satori, which is an **internal** knowledge graph in Microsoft.

**Comment by SSSxCCC** [comment]
Thank you for your reply! Now I know why I can't access the website.
