### ISSUE TITLE
感觉这一步计算量好大

### ISSUE THREAD

**Issue by lixusign** [hwwang55/GCNRec#18]
self.l2_loss = tf.nn.l2_loss(self.user_emb_matrix) + tf.nn.l2_loss(
            self.entity_emb_matrix) + tf.nn.l2_loss(self.relation_emb_matrix)

请问作者有啥可以优化的办法 或者 替换的办法呢？

比如 我的 emb 大小是 [100000000, 32]

**Comment by hwwang55** [comment]
您好，可以只考虑当前minibatch所涉及的用户，也就是self.user_embeddings。谢谢！

**Comment by lixusign** [comment]
是哦 谢谢 ，要是n_entity 和 n_relation 比较大就没辙了。

**Comment by hwwang55** [comment]
理论上也可以只考虑本minibatch涉及到的entity和relation的

**Comment by lixusign** [comment]
哦哦  我都试试 谢谢小主
