### ISSUE TITLE
问下关于KGNN_LS对比KGCN的提升

### ISSUE THREAD

**Issue by lixusign** [hwwang55/GCNRec#19]
KGNN_LS 的loss  需要引入interaction_hashtable.  这里需要读入全部的训练数据集，如果是训练数据集很大的话，会非常消耗资源（因为全量数据集需要进tensorflow内存）所以问下 这个loss的加入有多大的提升？

**Comment by lixusign** [comment]
感觉需要单独开发个组件，不加载到TF集群里

**Comment by hwwang55** [comment]
你好，如果KGNN-LS太慢，可以使用KGCN试试，它没有LS这个模块，性能上的差别要看具体的数据集了，可以用一个小一点的数据集先跑跑看。

**Comment by lixusign** [comment]
hihi， 小主，我刷了下论文，看到了interaction_table 不需要参与反向传播。 求小主确认下，如果是这样我单独构建了，在分布式训练中，不放到PS-server里面存了。

**Comment by hwwang55** [comment]
是的

**Comment by lixusign** [comment]
好的 谢谢
