### ISSUE TITLE
如果是增加了新的用户,整个模型是不是只能重新训练???

### ISSUE THREAD

**Issue by swy0915** [hwwang55/GCNRec#25]
如果是增加了新的用户,整个模型是不是只能重新训练???

**Comment by hwwang55** [comment]
您好！理论上是这样的

**Comment by swy0915** [comment]
好的 谢谢

**Comment by swy0915** [comment]
那kgcn还是存在冷启动的问题，有什么办法可以解决吗？？？

**Comment by hwwang55** [comment]
您好！用户的冷启动问题只能靠引入用户端的辅助信息，比如用户属性，用户社交网络等

**Comment by swy0915** [comment]
怎么把这些辅助信息用到kgcn里呢？比如新增了1个电影的用户  这个用户没有对电影的任何评价，但是有一些对电影属性的偏好，比如 喜欢看 武打片和科幻片 喜欢 李小龙。 但是这个用户的embedding 是不存在模型里的。kgcn是不是 只能重新训练 增加这个用户(对应多了这个用户的embedding)

**Comment by hwwang55** [comment]
这个不属于KGCN的研究范围，但是一个简单的办法是可以用一个MLP来处理用户的属性，输出用户的embedding

**Comment by swy0915** [comment]
好的，我也这样想的，非常谢谢
