### ISSUE TITLE
咨询一下kg.txt 每个字段的具体含义

### ISSUE THREAD

**Issue by Aliang-CN** [hwwang55/GCNRec#7]
你好，music里面txt里面每个字段具体什么含义呢，例如：2086	music.artist.origin	3846。
我看代码里面对应的是head_old，relation_old，tail_old。看着我很懵，可以做一个比较通俗易懂的解释吗？

**Comment by hwwang55** [comment]
你好，2086是head节点的ID，3846是tail节点的ID，music.artist.origin是relation
